#ifndef REDUCTION_WIDTH_H
#define REDUCTION_WIDTH_H
#define REDUCTION_WIDTH_ROOT_POW 10lu
#define REDUCTION_WIDTH (1lu << REDUCTION_WIDTH_ROOT_POW)
#define REDUCTION_WIDTH_POW(p) (1lu << (REDUCTION_WIDTH_ROOT_POW * p))
#endif
